### ISSUE TITLE
Структуриран README

### ISSUE THREAD

**Issue by WaLkZa** [profjordanov/hybrid-app-development#6]
Здравей, колега,

Поздравления за положения труд. Наистина курсът има стойност.
Имам предложение за по-структуриран README файл с презентации, упражнения и видео записи.
Един пример, който може да ти допадне: [https://github.com/github.com/fmi/java-course#съвременни-java-технологии--фми](https://github.com/fmi/java-course#%D1%81%D1%8A%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B8-java-%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8--%D1%84%D0%BC%D0%B8)

**Comment by profjordanov** [comment]
Много благодаря за обратната връзка. Ще се заема с тази задача в първия свободен момент, задължително.
